export const POST_ORDER_REQUEST = "POST_ORDER_REQUEST";
export const POST_ORDER_SUCCESS = "POST_ORDER_SUCCESS";
export const POST_ORDER_FAILURE = "POST_ORDER_FAILURE";

export const GET_USERORDER_REQUEST = "GET_USERORDER_REQUEST";
export const GET_USERORDER_SUCCESS = "GET_USERORDER_SUCCESS";
export const GET_USERORDER_FAILURE = "GET_USERORDER_FAILURE";

export const DELETE_USERORDER_REQUEST = "DELETE_USERORDER_REQUEST";
export const DELETE_USERORDER_SUCCESS = "DELETE_USERORDER_SUCCESS";
export const DELETE_USERORDER_FAILURE = "DELETE_USERORDER_FAILURE";

export const CHECKOUt_REQUEST = "CHECKOUT_REQUEST";
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS";
export const CHECKOUT_FAILURE = "CHECKOUT_FAILURE";

export const DELETE_USERORDER_MANY_REQUEST = "DELETE_USERORDER_MANY_REQUEST";
export const DELETE_USERORDER_MANY_SUCCESS = "DELETE_USERORDER_MANY_SUCCESS";
export const DELETE_USERORDER_MANY_FAILURE = "DELETE_USERORDER_MANY_FAILURE";
