export const POST_ORDER_REQUEST = "POST_ORDER_REQUEST";
export const POST_ORDER_SUCCESS = "POST_ORDER_SUCCESS";
export const POST_ORDER_FAILURE = "POST_ORDER_FAILURE";

export const GET_USERORDER_REQUEST = "GET_USERORDER_REQUEST";
export const GET_USERORDER_SUCCESS = "GET_USERORDER_SUCCESS";
export const GET_USERORDER_FAILURE = "GET_USERORDER_FAILURE";
