export const POST_SIGNUP_DETAILS_REQUEST = "POST_SIGNUP_DETAILS_REQUEST";
export const POST_SIGNUP_DETAILS_SUCCESS = "POST_SIGNUP_DETAILS_SUCCESS";
export const POST_SIGNUP_DETAILS_FAILURE = "POST_SIGNUP_DETAILS_FAILURE";

export const SIGNIN_DETAILS_REQUEST = "SIGNIN_DETAILS_REQUEST";
export const SIGNIN_DETAILS_SUCCESS = "SIGNIN_DETAILS_SUCCESS";
export const SIGNIN_DETAILS_FAILURE = "SIGNIN_DETAILS_FAILURE";

export const GET_USER_DETAILS_REQUEST = "GET_USER_DETAILS_REQUEST";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAILURE = "GET_USER_DETAILS_FAILURE";

export const LOGOUT = "LOGOUT";
