export const POST_SIGNUP_DETAILS_REQUEST = "POST_SIGNUP_DETAILS_REQUEST";
export const POST_SIGNUP_DETAILS_SUCCESS = "POST_SIGNUP_DETAILS_SUCCESS";
export const POST_SIGNUP_DETAILS_FAILURE = "POST_SIGNUP_DETAILS_FAILURE";
