export const MEN_DATA_REQUEST = "MEN_DATA_REQUEST";
export const MEN_DATA_SUCCESS = "MEN_DATA_SUCCESS";
export const MEN_DATA_FAILURE = "MEN_DATA_FAILURE";

export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";
